# index:
#    path: /
#    controller: App\Controller\DefaultController::index
# users_index:
#   path: /users
#   controller: App\Controller\UsersController::index
#   methods: GET|POST

# product_search:
#   path: /product/search
#   controller: App\Controller\ProductController::search
#   methods: POST
